[project]
name = "zhiqu-zhida"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "deepagents==0.6.0",
    "fastapi>=0.140.7",
    "langchain-openai>=1.4.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.6.1",
    "uvicorn[standard]>=0.51.0",
]
